version: '3'
services:
  express-app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - socialDB
    environment:
      DATABASE_URL: 'mongodb://social:socmongoc@socialDB:27017/mydatabase?authSource=admin&directConnection=true'
  socialDB:
    image: prismagraphql/mongo-single-replica:5.0.3
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: social
      MONGO_INITDB_ROOT_PASSWORD: socmongoc
